apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service # Service Logstash will connect to
  namespace: kfm-observability # Use the same namespace
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch # Selects the Elasticsearch pod(s)
  ports:
    - name: http
      protocol: TCP
      port: 9200       # Port the service listens on
      targetPort: 9200 # Port the Elasticsearch container listens on
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
  # Use ClusterIP for internal access
  type: ClusterIP 
  # Optional: Use LoadBalancer or NodePort for external access, 
  # usually Kibana handles external access. 