apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: kfm-observability # Use the same namespace
  labels:
    app: logstash
spec:
  selector:
    app: logstash # Selects the Logstash pods managed by the Deployment
  ports:
    - name: beats
      protocol: TCP
      port: 5044 # Port the service listens on
      targetPort: 5044 # Port the Logstash container listens on
    # Optional: Expose the monitoring port if needed internally
    # - name: http-monitoring
    #   protocol: TCP
    #   port: 9600
    #   targetPort: 9600
  type: ClusterIP # Expose internally within the cluster 