import { Create, SimpleForm, TextInput, required } from 'react-admin';
import { Grid } from '@mui/material';

export const AgentCreate = () => (
    <Create title="Create New Agent">
        <SimpleForm>
            <Grid container spacing={2}>
                {/* ID is usually generated by the backend, so it's not included here */}
                <Grid item xs={12} md={6}>
                    <TextInput source="name" validate={required()} fullWidth />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextInput source="type" validate={required()} fullWidth />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextInput source="version" validate={required()} fullWidth />
                </Grid>
                 <Grid item xs={12} md={6}>
                    <TextInput source="owner" fullWidth />
                </Grid>
                 <Grid item xs={12} md={6}>
                    <TextInput source="maintainer" fullWidth />
                </Grid>
                {/* State defaults to NEW, usually not set during creation */}
                {/* Add other fields like description, capabilities (maybe as ArrayInput), metadata (maybe as JsonInput) */}
                <Grid item xs={12}>
                    <TextInput source="description" multiline fullWidth />
                </Grid>
            </Grid>
        </SimpleForm>
    </Create>
); 