apiVersion: v1
kind: Service
metadata:
  name: f-operator-service
  namespace: kfm-operators # Use the same namespace as the Deployment
  labels:
    app: f-operator
spec:
  selector:
    app: f-operator # Selects pods with the 'app: f-operator' label
  ports:
    - name: http
      protocol: TCP
      port: 8000 # Port the service listens on
      targetPort: 8000 # Port the container listens on (from Deployment)
  # Expose internally within the cluster
  type: ClusterIP 