apiVersion: v1
kind: Secret
metadata:
  name: kfm-ae-secrets
  namespace: kfm-ae
type: Opaque
data:
  # Database Credentials (Base64 Encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # Example: 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # Example: 'password'
  NEO4J_USER: bmVvNGo=       # Example: 'neo4j'
  NEO4J_PASSWORD: c2VjcmV0=   # Example: 'secret'

  # API Keys (Base64 Encoded)
  INTERNAL_SERVICE_API_KEY: YXBpa2V5Zm9yYmFja2VuZA== # Example: 'apikeyforbackend'
  EXTERNAL_API_KEY_EXAMPLE: ZXh0ZXJuYWxhcGk=          # Example: 'externalapi'

  # Other Secrets (Base64 Encoded)
  JWT_SECRET_KEY: c29tZXNlY3JldGtleWZvcmp3dA== # Example: 'somesecretkeyforjwt'

  # Add other base64 encoded secrets here 