apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: m-operator-pdb
  namespace: kfm-operators # Use the same namespace as the Deployment
  labels:
    app: m-operator
spec:
  # Ensure at least 1 replica is available during disruptions
  minAvailable: 1 
  selector:
    matchLabels:
      app: m-operator # Selects the pods managed by the m-operator Deployment 